CREATE DATABASE dbserv;

USE dbserv;

CREATE TABLE ESTADO(
	idestado INT(6) NOT NULL AUTO_INCREMENT,
	nome 	 VARCHAR(30) NOT NULL,

	PRIMARY KEY(IDESTADO),
	UNIQUE KEY IDESTADO_UNIQUE 	(IDESTADO),
	UNIQUE KEY NOME_UNIQUE 		(NOME)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE PAGINA(
	idpagina  INT(6) NOT NULL AUTO_INCREMENT,
	site 	  VARCHAR(50),
	google 	  VARCHAR(50),
	twitter	  VARCHAR(50),
	pinterest VARCHAR(50),
	facebook  VARCHAR(50),
	instagram VARCHAR(50),

	PRIMARY KEY(IDPAGINA),
	UNIQUE KEY IDPAGINA_UNIQUE (IDPAGINA)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE CATEGORIA(
	idcategoria	INT(6) 		NOT NULL AUTO_INCREMENT,
	descricao 	VARCHAR(20) NOT NULL,

	PRIMARY KEY(IDCATEGORIA),
	UNIQUE KEY IDCATEGORIA_UNIQUE (IDCATEGORIA),
	UNIQUE KEY DESCRICAO_UNIQUE (DESCRICAO)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE CIDADE(
	idcidade 	INT(6) NOT NULL AUTO_INCREMENT,
	nome 		VARCHAR(40) NOT NULL,
	estado 		INT(6) NOT NULL,

	PRIMARY KEY(IDCIDADE),
	UNIQUE KEY IDCIDADE_UNIQUE (IDCIDADE),
	CONSTRAINT `fk_cidade_estado` FOREIGN KEY (ESTADO) REFERENCES ESTADO (IDESTADO)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE BAIRRO(
	idbairro 	INT(6) NOT NULL AUTO_INCREMENT,
	nome 		VARCHAR(30) NOT NULL,
	cidade 		INT(6) NOT NULL,

	PRIMARY KEY(IDBAIRRO),
	UNIQUE KEY IDBAIRRO_UNIQUE (IDBAIRRO),
	CONSTRAINT `fk_bairro_cidade` FOREIGN KEY (CIDADE) REFERENCES CIDADE (IDCIDADE)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE AREAATUACAO(
	idarea 		INT(6) NOT NULL AUTO_INCREMENT,
	descricao 	VARCHAR(50) NOT NULL,
	categoria 	INT(6) NOT NULL,

	PRIMARY KEY(IDAREA),
	UNIQUE KEY IDAREA_UNIQUE (IDAREA),
	UNIQUE KEY DESCRICAO_UNIQUE (DESCRICAO),
	CONSTRAINT `fk_areaatuacao_categoria` FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (IDCATEGORIA)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE ADMINISTRADOR(
	idadmin 	INT(6) NOT NULL AUTO_INCREMENT,
	nome	 	VARCHAR(30) NOT NULL,
	login 		VARCHAR(15) NOT NULL,
	senha 		VARCHAR(80) NOT NULL,
	perfil 		TINYINT NOT NULL DEFAULT 1,
	status_ 	TINYINT NOT NULL DEFAULT 1,
	dtcadastro  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(IDADMIN),
	UNIQUE KEY IDADMIN_UNIQUE (IDADMIN),
	UNIQUE KEY LOGIN_UNIQUE (LOGIN)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE ENDERECO(
	idendereco 	INT(6) NOT NULL AUTO_INCREMENT,
	cep 		VARCHAR(8) NOT NULL,
	logradouro 	VARCHAR(50) NOT NULL,
	numero 		VARCHAR(10) NOT NULL,
	complemento VARCHAR(50),
	bairro 		INT(6) NOT NULL,

	PRIMARY KEY(IDENDERECO),
	UNIQUE KEY IDENDERECO_UNIQUE (IDENDERECO),
	CONSTRAINT `fk_endereco_bairro` FOREIGN KEY (BAIRRO) REFERENCES BAIRRO (IDBAIRRO)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE CLIENTE(
	idcliente 	INT(6) NOT NULL AUTO_INCREMENT,
	cpf 		VARCHAR(11) NOT NULL,
	foto 		VARCHAR(30) NOT NULL,
	nome	 	VARCHAR(50) NOT NULL,
	fone 		VARCHAR(11) NOT NULL,
	email 		VARCHAR(60) NOT NULL,
	login 		VARCHAR(15) NOT NULL,
	senha 		VARCHAR(80) NOT NULL,
	perfil 		TINYINT NOT NULL DEFAULT 2,
	status_ 	TINYINT NOT NULL DEFAULT 1,
	dtcadastro  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	endereco    INT(6) NOT NULL,

	PRIMARY KEY(IDCLIENTE),
	UNIQUE KEY IDCLIENTE_UNIQUE (IDCLIENTE),
	UNIQUE KEY CPF_UNIQUE (CPF),
	UNIQUE KEY FOTO_UNIQUE (FOTO),
	UNIQUE KEY LOGIN_UNIQUE (LOGIN),
	CONSTRAINT `fk_cliente_endereco` FOREIGN KEY (ENDERECO) REFERENCES ENDERECO (IDENDERECO)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE FISICO(
	idfisico 	INT(6) NOT NULL AUTO_INCREMENT,
	descricao 	LONGTEXT NOT NULL,
	fixo 		VARCHAR(10),
	fone 		VARCHAR(11) NOT NULL,
	email 		VARCHAR(60) NOT NULL,
	nome	 	VARCHAR(50) NOT NULL,
	cpf 		VARCHAR(11) NOT NULL,
	foto 		VARCHAR(30) NOT NULL,
	login 		VARCHAR(15) NOT NULL,
	senha 		VARCHAR(80) NOT NULL,
	perfil 		TINYINT NOT NULL DEFAULT 3,
	status_ 	TINYINT NOT NULL DEFAULT 3,
	dtcadastro  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	endereco    INT(6) NOT NULL,
	area 	    INT(6) NOT NULL,
	pagina 	    INT(6) NOT NULL,
	admin 	    INT(6),

	PRIMARY KEY(IDFISICO),
	UNIQUE KEY IDFISICO_UNIQUE (IDFISICO),
	UNIQUE KEY CPF_UNIQUE (CPF),
	UNIQUE KEY FOTO_UNIQUE (FOTO),
	UNIQUE KEY LOGIN_UNIQUE (LOGIN),
	CONSTRAINT `fk_fisico_endereco` FOREIGN KEY (ENDERECO) REFERENCES ENDERECO (IDENDERECO),
	CONSTRAINT `fk_fisico_area` FOREIGN KEY (AREA) REFERENCES AREAATUACAO (IDAREA),
	CONSTRAINT `fk_fisico_pagina` FOREIGN KEY (PAGINA) REFERENCES PAGINA (IDPAGINA),
	CONSTRAINT `fk_fisico_admin` FOREIGN KEY (ADMIN) REFERENCES ADMINISTRADOR (IDADMIN)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE JURIDICO(
	idjuridico 	 INT(6) NOT NULL AUTO_INCREMENT,
	descricao 	 LONGTEXT NOT NULL,
	fixo 		 VARCHAR(10),
	fone 		 VARCHAR(11) NOT NULL,
	email 		 VARCHAR(60) NOT NULL,
	responsavel	 VARCHAR(50) NOT NULL,
	logo 		 VARCHAR(30) NOT NULL,
	nomefantasia VARCHAR(80) NOT NULL,
	cnpj 		 VARCHAR(14) NOT NULL,
	razaosocial  VARCHAR(80) NOT NULL,
	login 		 VARCHAR(15) NOT NULL,
	senha 		 VARCHAR(80) NOT NULL,
	perfil 		 TINYINT NOT NULL DEFAULT 3,
	status_ 	 TINYINT NOT NULL DEFAULT 3,
	dtcadastro   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	endereco     INT(6) NOT NULL,
	area 	     INT(6) NOT NULL,
	pagina 	     INT(6) NOT NULL,
	admin 	     INT(6),

	PRIMARY KEY(IDJURIDICO),
	UNIQUE KEY IDJURIDICO_UNIQUE (IDJURIDICO),
	UNIQUE KEY LOGO_UNIQUE (LOGO),
	UNIQUE KEY CNPJ_UNIQUE (CNPJ),
	UNIQUE KEY LOGIN_UNIQUE (LOGIN),
	CONSTRAINT `fk_juridico_endereco` FOREIGN KEY (ENDERECO) REFERENCES ENDERECO (IDENDERECO),
	CONSTRAINT `fk_juridico_area` FOREIGN KEY (AREA) REFERENCES AREAATUACAO (IDAREA),
	CONSTRAINT `fk_juridico_pagina` FOREIGN KEY (PAGINA) REFERENCES PAGINA (IDPAGINA),
	CONSTRAINT `fk_juridico_admin` FOREIGN KEY (ADMIN) REFERENCES ADMINISTRADOR (IDADMIN)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE SERVICO(
	idservico 	INT(11) NOT NULL AUTO_INCREMENT,
	descricao 	LONGTEXT NOT NULL,
	dtinicio 	DATE NOT NULL,
	dtfim 		DATE,
	vlsugerido 	DOUBLE(8,2) DEFAULT 0, 
	vlprofissional DOUBLE(8,2) DEFAULT 0,
	nota 		TINYINT,
	comentario  LONGTEXT,
	status_ 	TINYINT NOT NULL DEFAULT 1,
	cliente 	 INT(6) NOT NULL,
	fisico 		 INT(6),
	juridico	 INT(6),
	area 	     INT(6) NOT NULL,
	endereco     INT(6) NOT NULL,

	PRIMARY KEY(IDSERVICO),
	UNIQUE KEY IDSERVICO_UNIQUE (IDSERVICO),
	CONSTRAINT `fk_servico_cliente` FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (IDCLIENTE),
	CONSTRAINT `fk_servico_fisico` FOREIGN KEY (FISICO) REFERENCES FISICO (IDFISICO),
	CONSTRAINT `fk_servico_juridico` FOREIGN KEY (JURIDICO) REFERENCES JURIDICO (IDJURIDICO),
	CONSTRAINT `fk_servico_area` FOREIGN KEY (AREA) REFERENCES AREAATUACAO (IDAREA),
	CONSTRAINT `fk_servico_endereco` FOREIGN KEY (ENDERECO) REFERENCES ENDERECO (IDENDERECO)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


